/*
 * generated by Xtext 2.25.0
 */
package org.tetrabox.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MinitlStandaloneSetup extends MinitlStandaloneSetupGenerated {

	public static void doSetup() {
		new MinitlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
